# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy the rest of the code
COPY . .

# Build the project
RUN npm run build

# Expose port 80 for HTTP server
EXPOSE 80

# Run the HTTP server by default on port 80
CMD ["node", "dist/index.js", "--http", "--port", "80"]
