# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy the rest of the code
COPY . .

# Build the project
RUN npm run build

# Expose port 3000 for HTTP server
EXPOSE 3000

# Set environment variable placeholder (user should override these values in production)
ENV YNAB_API_TOKEN=""
# optional:
# ENV YNAB_BUDGET_ID=""
# ENV PORT=3000

# Run the HTTP server by default
CMD ["node", "dist/index.js", "--http", "--port", "3000"]
